language: python
python:
  - "3.5"
install:
  - "pip install -e .[test]"
  - "pip install codacy-coverage"
script: "./run-tests.sh"
after_script:
  - "python-codacy-coverage -r coverage.xml"
notifications:
  email: false